#pragma once

#define CSEND_VERSION_MAJOR 2
#define CSEND_VERSION_MINOR 0
#define CSEND_VERSION_PATCH 0
#define CSEND_VERSION_BUILD 0

#define CSEND_VERSION_TEXT "2.0.0"
#define CSEND_VERSION_FILEVERSION \
	CSEND_VERSION_MAJOR, CSEND_VERSION_MINOR, CSEND_VERSION_PATCH, CSEND_VERSION_BUILD
