#pragma once

#define CSEND_VERSION_MAJOR 1
#define CSEND_VERSION_MINOR 10
#define CSEND_VERSION_PATCH 0
#define CSEND_VERSION_BUILD 0

#define CSEND_VERSION_TEXT "1.10.0"
#define CSEND_VERSION_FILEVERSION \
	CSEND_VERSION_MAJOR, CSEND_VERSION_MINOR, CSEND_VERSION_PATCH, CSEND_VERSION_BUILD
